### ISSUE TITLE
I need an action to be able to stop the flow

### ISSUE THREAD

**Issue by MarcinLachowicz** [SabreOSS/yare#53]
I would like to be able to stop processing flow from within action implementation.
For example:
Given action:
```
public class Action {
        public void collect(List<Flight> result, Flight fact) {
               if (isInvalid(fact)) {
                      // stop the processing e.g. throw exception or set sth in context
               }
        }
}
```

**Comment by knoorek** [comment]
Guys! I need your opinion here. 

The easiest approach would be to create some custom YARE package accessed `RuntimeException` and provide a static method to throw it (e.g. in `RulesSession` class). 

To break the flow the user would have to invoke the static method in the action code. The exception wouldn't be available to the user in any other way (package access). So, for the user the code would look like:

```
public class Action {
        public void collect(List<Flight> result, Flight fact) {
               if (isInvalid(fact)) {
                      RulesSession.break();
               }
        }
}
```

The custom `RuntimeException` could be caught in `DefaultRulesExecutor`.

What I don't like about this solution is that the 'flow break' becomes a part of custom user code while it seems more like a part of `RulesEngine` configuration to me. Moreover, because the 'RulesSession.break()' is in the `Action` itself, we don't get to know anything about it just by looking at the DSL configuration.

The way I would approach this case would be to create an `ExceptionHandler` mechanism pluggable into the DSL configuration. The handler would be defined just like other mappings. One way to implement this idea would be to have a handler attached to the `Action` mapping itself. The handler would catch a specific exception and has another `Action` to execute on 'exception occurred' situation. The default handler available to plug in could call an Action breaking the engine flow (somehow internally).

What do you think? Any other ideas?

**Comment by krzysztofreczek** [comment]
I do like the ExceptionHandler idea. But I was thinking about yet another use-case that does not really fit the exception-oriented approach. Let's assume we are looking for the first applicable resource in a huge set of data. As soon as we found the first resource satisfying our request we do not want to continue to not waste time and CPU. In this case, we want to break the process due to a positive reason. Hence exception approach would not fit here.

**Comment by adamszadkowski** [comment]
When this feature request appeared for the first time I thought about different solution. From API perspective I think that the best would be to allow user inject a special object which can be used to terminate processing. In future there can be more useful API. Look at this:

```java
public class Action {
        public void collect(List<Flight> result, Flight fact, EngineController controller) {
               if (isInvalid(fact)) {
                      controller.stopProcessing();
               }
        }
}
```

You would register such action with for example "${engineController}" as a parameter.

I think this is better solution than throwing exception because exceptions should not be used to drive business logic. Also this can be extended in future.

**Comment by MarcinLachowicz** [comment]
Thank you all for opinions.
I do love @adamszadkowski idea. `EngineController` will allow to stop processing flow smoothly. Brilliant. Let's do it that way!

**Comment by adamszadkowski** [comment]
I think that you should choose different name for this object and provide it as a interface to allow testing user action methods. Maybe it would be good to provide some testing implementation (so client will not need to mock it). Then fake implementation could implement observer pattern and allow users to register listeners. Those listeners would receive callback on `stopProcessing()` method execution. This approach would benefit even more if new functionality would be added and it should be really fast to implement.

**Comment by wojciechzachwieja** [comment]
Implemented using `EngineController` way.
